config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from config.ddtb import DEBUG_TOOLBAR_PATH

from freelance.views import RegisterView


urlpatterns = [
    path('', include('freelance.urls')),
    path('ratings/', include('ratings.urls')),
    path('admin/', admin.site.urls),
    path('services/', include('services.urls'),name='service'),
    path('api-auth/', include('rest_framework.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    DEBUG_TOOLBAR_PATH, 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from . import views

app_name = 'services'
urlpatterns = [
    path('', views.service_list, name='service_list'),
    path('create/', views.service_create, name='service_create'),
    path('<int:pk>/update/', views.service_update, name='service_update'),
    path('<int:pk>/delete/', views.service_delete, name='service_delete'),
]

services/models.py
from django.db import models

class Service(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название услуги")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(upload_to='services/', blank=True, null=True, verbose_name="Изображение")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Создано")
    updated = models.DateTimeField(auto_now=True, verbose_name="Обновлено")

    def __str__(self):
        return self.title

services/forms.py
from django import forms
from .models import Service

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['title', 'description', 'image']

services/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Service
from .forms import ServiceForm

def service_list(request):
    services = Service.objects.all()
    return render(request, 'services/service_list.html', {'services': services})

def service_create(request):
    if request.method == 'POST':
        form = ServiceForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('services:service_list'))
    else:
        form = ServiceForm()
    return render(request, 'services/service_form.html', {'form': form})

def service_update(request, pk):
    service = get_object_or_404(Service, pk=pk)
    if request.method == 'POST':
        form = ServiceForm(request.POST, request.FILES, instance=service)
        if form.is_valid():
            form.save()
            return redirect(reverse('services:service_list'))
    else:
        form = ServiceForm(instance=service)
    return render(request, 'services/service_form.html', {'form': form})

def service_delete(request, pk):
    service = get_object_or_404(Service, pk=pk)
    if request.method == 'POST':
        service.delete()
        return redirect(reverse('services:service_list'))
    return render(request, 'services/service_confirm_delete.html', {'service': service})

templates/services/service_confirm_delete.html
{% extends 'basic/base.html' %}
{% block content %}
<h1>Удалить услугу</h1>
<p>Вы уверены, что хотите удалить "{{ service.title }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Да, удалить</button>
</form>
<a href="{% url 'services:service_list' %}">Назад к услугам</a>
{% endblock %}

templates/services/service_form.html
{% extends 'basic/base.html' %}
{% block content %}
<h1>{{ form.instance.pk|yesno:'Редактировать,Создать' }} услугу</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">Сохранить</button>
</form>
<a href="{% url 'services:service_list' %}">Назад к услугам</a>
{% endblock %}

templates/services/service_list.html
{% extends 'basic/base.html' %}

{% block title %}Услуги{% endblock %}

{% block content %}
<h1 class="text-center">Список услуг</h1>
<div class="col-md-8 offset-md-1">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Изображение</th>
                <th scope="col">Название</th>
                <th scope="col">Описание</th>
                <th scope="col">Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for service in services %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><img src="{{ service.image.url }}" alt="{{ service.title }}" width="100"></td>
                <td>{{ service.title }}</td>
                <td>{{ service.description }}</td>
                <td>
                    <a href="{% url 'services:service_update' service.pk %}">Подробнее</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}