config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from config.ddtb import DEBUG_TOOLBAR_PATH

from freelance.views import RegisterView


urlpatterns = [
    path('', include('freelance.urls')),
    path('ratings/', include('ratings.urls')),
    path('admin/', admin.site.urls),
    path('services/', include('services.urls'),name='service'),
    path('api-auth/', include('rest_framework.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    DEBUG_TOOLBAR_PATH, 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freelance/urls.py
from django.urls import path
from .views import (
    CustomLogoutView,
    MainPageView,
    ServiceListView,
    ServiceDetailView,
    OrderListView,
    OrderDetailView,
    OrderCreateView,
    OrderEditView,
    OrderRequestView,
    ExecutorListView,
    ExecutorDetailView,
    ExecutorsRequestsListView,
    CustomerListView,
    CustomerDetailView,
    CustomerAccessOrderView,
    CustomerAccessOrdersView,
)

app_name = "freelance"

urlpatterns = [
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path("", MainPageView.as_view(), name="main_page"),
    # Executors
    path("executors/", ExecutorListView.as_view(), name="executor-list"),
    path("executors/<int:pk>/", ExecutorDetailView.as_view(), name="executor-detail"),
    path("executors/requests/", ExecutorsRequestsListView.as_view(), name="executor-requests"),
    # Customers
    path("customers/", CustomerListView.as_view(), name="customer-list"),
    path("customers/<int:pk>/", CustomerDetailView.as_view(), name="customer-detail"),
    path("customers/access-orders/", CustomerAccessOrdersView.as_view(), name="customer-access-orders"),
    path("customers/access-order/<int:pk>/", CustomerAccessOrderView.as_view(), name="customer-access-order"),

    #path("services/", ServiceListView.as_view(), name="service-list"),
    path("services/<int:pk>/", ServiceDetailView.as_view(), name="service-detail"),
    # Orders
    path("orders/create/", OrderCreateView.as_view(), name="order-create"),
    path("orders/edit/<int:pk>", OrderEditView.as_view(), name="order-edit"),
    path("orders/", OrderListView.as_view(), name="order-list"),
    path("orders/<int:pk>", OrderDetailView.as_view(), name="order-detail"),
    path("orders/request/<int:pk>", OrderRequestView.as_view(), name="order-request"),
    path("orders/success/", OrderListView.as_view() , name="order-success"),
]

ratings/urls.py
from django.urls import path

from ratings.views import RatingListView, RatingUpdateView

app_name = "ratings"

urlpatterns = [
    path("all/", RatingListView.as_view(), name="rating_list"),
    path("update/<int:order>/", RatingUpdateView.as_view(), name="rating_update"),
]

freelance/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import validate_slug


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
        validators=[validate_slug],
    )
    phone = models.CharField(
        max_length=12, blank=True, null=True, verbose_name="Телефон"
    )
    rating = models.FloatField(default=5.0, verbose_name="Рейтинг")

    def __str__(self):
        phone_display = self.phone if self.phone else "Нет телефона"
        return f"{self.user.username} - {phone_display}"


class Executor(models.Model):
    profile = models.OneToOneField(
        UserProfile,
        on_delete=models.CASCADE,
        verbose_name="Профиль",
    )
    skills = models.TextField(blank=True, verbose_name="Навыки")
    avatar = models.ImageField(
        upload_to="user_avatars", null=True, blank=True, verbose_name="Аватар"
    )

    def __str__(self):
        return (
            super().__str__()
            + f" - Навыки: {self.skills if self.skills else 'Не указаны'}"
        )

    class Meta:
        verbose_name = "Исполнитель"
        verbose_name_plural = "Исполнители"


class Customer(models.Model):
    profile = models.OneToOneField(
        UserProfile,
        on_delete=models.CASCADE,
        verbose_name="Профиль",
    )
    preferences = models.TextField(blank=True, verbose_name="Предпочтения")

    def __str__(self):
        return f"{self.profile.user.username} - email: {self.profile.user.email if self.profile.user.email else 'Не указаны'}"

    class Meta:
        verbose_name = "Заказчик"
        verbose_name_plural = "Заказчики"


class Service(models.Model):
    class ServicesType(models.TextChoices):
        DESIGN = "design", "Дизайн"
        DEVELOPMENT = "development", "Разработка"
        SUPPORT = "support", "Поддержка"

    executor = models.ForeignKey(
        Executor, on_delete=models.CASCADE, verbose_name="Исполнитель"
    )
    name = models.CharField(
        max_length=255, blank=True, null=True, verbose_name="Название"
    )
    description = models.TextField(verbose_name="Описание")
    service_type = models.CharField(
        max_length=11,
        choices=ServicesType.choices,
        default="design",
        verbose_name="Тип услуги",
    )
    price = models.DecimalField(
        verbose_name="Стоимость", max_digits=10, decimal_places=2, default=0
    )

    def __str__(self):
        return self.name or "Неименованная услуга"

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"


class Order(models.Model):
    # service = models.OneToOneField(
    #     Service, on_delete=models.CASCADE, primary_key=True, verbose_name="Услуга"
    # )
    order_type = models.CharField(
        max_length=11,
        choices=Service.ServicesType.choices,
        default="design",
        verbose_name="Тип заказа",
    )

    title = models.CharField(max_length=255, verbose_name="Заголовок")
    description = models.TextField(verbose_name="Описание")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Создан", null=True
    )
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Обновлен", null=True)
    price = models.DecimalField(
        verbose_name="Стоимость", max_digits=10, decimal_places=2, default=0
    )

    customer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        related_name="customers",
        blank=True,
        null=True,
        verbose_name="Заказчик",
    )

    executor = models.ForeignKey(
        Executor,
        on_delete=models.CASCADE,
        related_name="executors",
        blank=True,
        null=True,
        verbose_name="Исполнитель",
    )

    def __str__(self):
        return self.title or self.description or "Неизвестный заказ"

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"


class OrderRequest(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="requests", verbose_name="Заказ"
    )
    executor = models.ForeignKey(
        Executor,
        on_delete=models.CASCADE,
        related_name="order_requests",
        verbose_name="Исполнитель",
        default=None,
        null=True,
    )
    about_executor = models.TextField(
        verbose_name="Об исполнителе", blank=True, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    status = models.CharField(
        max_length=20,
        choices=[
            ("pending", "В ожидании"),
            ("accepted", "Принято"),
            ("rejected", "Отклонено"),
        ],
        default="pending",
        verbose_name="Статус",
    )

    class Meta:
        unique_together = ("order", "executor")
        verbose_name = "Заявка на заказ"
        verbose_name_plural = "Заявки на заказы"

    def __str__(self):
        return f"{self.order.title} - {self.executor.profile.user.username}"


class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name="Имя тега")
    service = models.ForeignKey(
        Service,
        on_delete=models.CASCADE,
        related_name="tags",
        blank=True,
        null=True,
        verbose_name="Услуга",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"

freelance/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile, Customer, Executor, Order, OrderRequest


class UserRegistrationForm(UserCreationForm):
    USER_CHOICES = [
        ("customer", "Заказчик"),
        ("executor", "Исполнитель"),
    ]
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Email"}
        ),
    )
    phone_number = forms.CharField(
        label="Номер телефона",
        max_length=15,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Номер телефона"}
        ),
    )
    first_name = forms.CharField(
        label="Имя",
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Имя"}),
    )
    last_name = forms.CharField(
        label="Фамилия",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Фамилия"}
        ),
    )

    user_type = forms.ChoiceField(choices=USER_CHOICES)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Имя пользователя"}
        )
        self.fields["password1"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Пароль"}
        )
        self.fields["password2"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Подтверждение пароля"}
        )
        self.fields["user_type"].widget.attrs.update(
            {"class": "form-select form-control"}
        )

        # Добавляем классы Bootstrap для меток
        self.fields["username"].label = "Имя пользователя"
        self.fields["password1"].label = "Пароль"
        self.fields["password2"].label = "Подтверждение пароля"
        self.fields["user_type"].label = "Тип пользователя"

        # Прижимаем метки вправо
        self.fields["username"].label_suffix = ""
        self.fields["password1"].label_suffix = ""
        self.fields["password2"].label_suffix = ""
        self.fields["user_type"].label_suffix = ""
        self.fields["email"].label_suffix = ""
        self.fields["phone_number"].label_suffix = ""

        # Добавляем классы Bootstrap для ошибок
        self.fields["username"].error_messages = {
            "required": "Это поле обязательно для заполнения"
        }
        self.fields["password1"].error_messages = {
            "required": "Это поле обязательно для заполнения"
        }
        self.fields["password2"].error_messages = {
            "required": "Это поле обязательно для заполнения"
        }
        self.fields["user_type"].error_messages = {
            "required": "Это поле обязательно для заполнения"
        }
        self.fields["email"].error_messages = {
            "required": "Это поле обязательно для заполнения"
        }
        self.fields["phone_number"].error_messages = {
            "required": "Это поле обязательно для заполнения"
        }

    def save(self, commit=True):
        user = super().save(commit=commit)  # Сохраняем пользователя в базе данных
        # Создаем профиль пользователя и связываем его с созданным пользователем
        user_profile = UserProfile.objects.create(
            user=user,
            phone=self.cleaned_data["phone_number"],
        )  # Создаем профиль пользователя и сохраняем в него номер телефона
        user_profile.user.email = self.cleaned_data["email"]
        user_profile.user.first_name = self.cleaned_data["first_name"]
        user_profile.user.last_name = self.cleaned_data["last_name"]
        user_profile.user.save()
        return user


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["order_type", "title", "description", "price"]

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

    def save(self, commit=True):
        order = super().save(commit=False)
        if commit:
            order.save()
        return order

    def delete(self, commit=True):
        order = super().save(commit=False)
        if commit:
            order.delete()
        return order


class OrderRequestForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["order"].widget = forms.HiddenInput()
        self.fields["executor"].widget = forms.HiddenInput()
        self.fields["about_executor"].widget = forms.Textarea(
            attrs={"rows": 5, "class": "form-control"}
        )
        self.fields["status"].widget.attrs["disabled"] = True
        self.fields["status"].required = False

    class Meta:
        model = OrderRequest
        fields = "__all__"


    def save(self, commit=True):
        order_request = super().save(commit=False)
        if commit:
            order_request.save()
        return order_request

templates/freelance/orders/order_create.html
{% extends 'basic/base.html' %}

{% block title %}{{ title_label }}{% endblock %}

{% block content %}
<h1>{{ title_label }}</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" сlass="btn btn-primary">{{ title_label }}</button>
</form>
{% endblock %}

templates/freelance/orders/order_detail.html
{% extends 'basic/base.html' %}
{% load custom_tags %}

{% block title %}Детали Заказа: {{ order.service.name }}{% endblock %}

{% block content %}
<div class="row-fluid mt-5 mb-5">
    <div class="col-md-6 offset-md-3">
        <h4>Заказ: {{ order.title }}</h4>
        <p><h5>Описание услуги:</h5> {{ order.description }}</p>
        <p>Стоимость: <h4>{{ order.price }}</h4></p>
        <p>Тип заказа: {{ order.get_order_type_display }}</p>
        
        <!-- Добавьте другие детали заказа по мере необходимости -->
    </div>

    {% if user.is_authenticated and user|has_group:"Customers" %}
        <div class="col-md-6 offset-md-3">
            <a class="btn btn-primary" href="{% url 'freelance:order-edit' order.pk %}">Редактировать</a>
        </div>
    {% elif user.is_authenticated and user|has_group:"Executors" %}
        <a class="btn btn-warning btn-sm" href="{% url 'ratings:rating_update' order.pk %}"> Рейтинг </a>
    {% endif %}
</div>
{% endblock %}

templates/freelance/orders/order_list.html
{% extends 'basic/base.html' %}
{% load custom_tags %}

{% block title %}{{ title_label }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3 mt-5 mb-2 text-center">
        <h1>{{ title_label }}</h1>
    </div>
    <div class="orders mb-5 text-left col-md-10 offset-md-1">
        <table class="table">
            <tbody>
            {% if not order_views %}
                <tr>
                    <td colspan="5">Заказов нет</td>
                </tr>
            {% else %}
                <tr>
                    <th>Заказ</th>
                    <th>Описание</th>
                    <th>Стоимость</th>
                    <th>Посмотреть </th>
                    {% if user.is_authenticated and user|has_group:"Customers" and user == order.customer.profile.user %}                        
                        <th>Редактировать</th>
                    {% endif %}
                    {% if user.is_authenticated and user|has_group:"Executors" %}
                        <th>Заявки</th>
                    {% endif %}
                </tr>
                {% for order, show_button in order_views %}                
                <tr>
                    <td>
                        <h5>{{ order.title }}</h5>
                    </td>
                    <td>
                        {{ order.service.description }}
                        <span class="minfo">Тип заказа: {{ order.get_order_type_display }}</span>
                    </td>
                    <td>
                        <h6>{{ order.price }}</h6>

                    </td>
                    <td>
                        <a class="btn btn-info" href="{% url 'freelance:order-detail' order.pk %}">Посмотреть</a>
                    </td>
                        {% if user.is_authenticated and user|has_group:"Customers" and user == order.customer.profile.user %}
                        <td>
                            <a class="btn btn-info" href="{% url 'freelance:order-edit' order.pk %}">Редактировать</a>
                        </td>
                        {% endif %}
                        {% if user.is_authenticated and user|has_group:"Executors" %}
                        <td>
                            {% if show_button %}
                                <span class="{% if show_button == 'Принято' %}text-success{% elif show_button == 'Отклонено' %}text-danger{% else %}text-warning{% endif %}">{{ show_button }}</span>
                            {% else %}
                                <a class="btn btn-info" href="{% url 'freelance:order-request' order.pk %}">Отправить запрос</a>
                            {% endif %}
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/freelance/orders/order_request.html
{% extends 'basic/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1>Заказ: {{ order.title }}</h1>
            <p><h4>Описание услуги:</h4> {{ order.description }}</p>
            <p>Стоимость: <h4>{{ order.price }}</h4></p>
            <p>Тип заказа: {{ order.get_order_type_display }}</p>
            <!-- Добавьте другие детали заказа по мере необходимости -->
            <form method="post" action="{% url 'freelance:order-request' order.pk %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Отправить запрос</button>
            </form>
    </div>
{% endblock %}