config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from config.ddtb import DEBUG_TOOLBAR_PATH

from freelance.views import RegisterView


urlpatterns = [
    path('', include('freelance.urls')),
    path('ratings/', include('ratings.urls')),
    path('admin/', admin.site.urls),
    path('services/', include('services.urls'),name='service'),
    path('api-auth/', include('rest_framework.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    DEBUG_TOOLBAR_PATH, 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freelance/urls.py
from django.urls import path
from .views import (
    CustomLogoutView,
    MainPageView,
    ServiceListView,
    ServiceDetailView,
    OrderListView,
    OrderDetailView,
    OrderCreateView,
    OrderEditView,
    OrderRequestView,
    ExecutorListView,
    ExecutorDetailView,
    ExecutorsRequestsListView,
    CustomerListView,
    CustomerDetailView,
    CustomerAccessOrderView,
    CustomerAccessOrdersView,
)

app_name = "freelance"

urlpatterns = [
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path("", MainPageView.as_view(), name="main_page"),
    # Executors
    path("executors/", ExecutorListView.as_view(), name="executor-list"),
    path("executors/<int:pk>/", ExecutorDetailView.as_view(), name="executor-detail"),
    path("executors/requests/", ExecutorsRequestsListView.as_view(), name="executor-requests"),
    # Customers
    path("customers/", CustomerListView.as_view(), name="customer-list"),
    path("customers/<int:pk>/", CustomerDetailView.as_view(), name="customer-detail"),
    path("customers/access-orders/", CustomerAccessOrdersView.as_view(), name="customer-access-orders"),
    path("customers/access-order/<int:pk>/", CustomerAccessOrderView.as_view(), name="customer-access-order"),

    #path("services/", ServiceListView.as_view(), name="service-list"),
    path("services/<int:pk>/", ServiceDetailView.as_view(), name="service-detail"),
    # Orders
    path("orders/create/", OrderCreateView.as_view(), name="order-create"),
    path("orders/edit/<int:pk>", OrderEditView.as_view(), name="order-edit"),
    path("orders/", OrderListView.as_view(), name="order-list"),
    path("orders/<int:pk>", OrderDetailView.as_view(), name="order-detail"),
    path("orders/request/<int:pk>", OrderRequestView.as_view(), name="order-request"),
    path("orders/success/", OrderListView.as_view() , name="order-success"),
]

ratings/urls.py
from django.urls import path

from ratings.views import RatingListView, RatingUpdateView

app_name = "ratings"

urlpatterns = [
    path("all/", RatingListView.as_view(), name="rating_list"),
    path("update/<int:order>/", RatingUpdateView.as_view(), name="rating_update"),
]

services/urls.py
from django.urls import path
from . import views

app_name = 'services'
urlpatterns = [
    path('', views.service_list, name='service_list'),
    path('create/', views.service_create, name='service_create'),
    path('<int:pk>/update/', views.service_update, name='service_update'),
    path('<int:pk>/delete/', views.service_delete, name='service_delete'),
]

templates/basic/includes/login.html
{% load custom_tags %}
{% if user.is_authenticated%}
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
        data-bs-toggle="dropdown" aria-expanded="false">
        Профиль: {{ user.username }}
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li>
            <a href="{% url 'ratings:rating_list' %}">Просмотреть отзывы</a>
        </li>
        {% if user|has_group:"Customers" %}
        <li>
            <a href="{% url 'freelance:order-create' %}">Создать заказ</a>
        </li>
        <li>
            <a href="{% url 'freelance:customer-access-orders' %}">Просмотреть заказы</a>
        </li>
        {% endif %}
        {% if user|has_group:"Executors" %}
        <li>
            <a href="{% url 'freelance:executor-requests' %}">Мои Заказы</a>
        </li>
        {% endif %}
        <li>
            <form action="{% url 'freelance:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Выйти</button>
            </form>
        </li>
        <!-- <li><a class="dropdown-item" href="{% url 'freelance:logout' %}">Выход</a></li> -->
    </ul>
</div>
{% else %}
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
        data-bs-toggle="dropdown" aria-expanded="false">
        Профиль
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li>
            <a href="{% url 'register' %}">Регистрация</a>
        </li>
        <li>
            <a class="btn btn-primary" href="{% url 'login' %}">Вход</a>
        </li>
    </ul>
</div>
{% endif %}

templates/basic/includes/mainmenu.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Мой Сайт</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Главная</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Услуги
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'services:service_list' %}">Все Услуги</a></li>
                            <!-- Добавьте сюда другие ссылки на услуги -->
                        </ul>
                    </li>
                    <!-- Продолжайте добавлять другие элементы меню здесь -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownOrdersLink" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Заказы
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownOrdersLink">
                            <li><a class="dropdown-item" href="{% url 'freelance:order-list' %}">Все Заказы</a></li>
                            <!-- Добавьте сюда другие ссылки на заказы -->
                        </ul>
                    </li>
                </ul>
            </div>
            {% include 'basic/includes/login.html' %}
        </div>
    </nav>
</header>